project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true
  render:
    - "*.qmd"

execute:
  freeze: auto
  warning: false

website:
  title: "Ariana Bardauil"
  favicon: imagenes/logo.png
  site-url: ariibard.github.io
  repo-url: https://github.com/ariibard/ariibard.github.io
  #google-analytics: "G-EX523L4LWJ"
  open-graph: true
  navbar:
    left:
      - text: CV
        file: cv.qmd
        
      - icon: github
        href: https://github.com/ariibard/
        aria-label: GitHub
        
      - icon: linkedin
        href: https://www.linkedin.com/in/ariana-bardauil/
        
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
        
      - text: Sobre mi
        file: about_es.qmd


      - text: Proyectos
        file: proyectos.qmd
        
      - text: Publicaciones
        file: publicaciones.qmd

      - text: Cursos, talleres & charlas
        file: cursos.qmd



  page-footer:
    left: |
      <div style="font-size: 1.2em; line-height: 1.4;">
      <strong>&copy; 2025 Ariana Bardauil</strong><br>
      <span>
        Website adapted from <a href="https://github.com/kazuyanagimoto/kazuyanagimoto.github.io" target="_blank">Kazuharu Yanagimoto</a>, 
      </span>
      <span>
      <br>licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a>.
      </span>
      </div>
    center: |
      <span class="faux-block">[{{< fa brands github >}}]({{< var github-url >}}) [{{< fa brands linkedin >}}]({{< var linkedin-url >}}) </span>
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">View the source at [{{< fa brands github >}} GitHub]({{< var repo-url >}})</span>
      
format:
  html:
    theme: 
      - styles.scss
    css: estilos/publis.css




