project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto
  warning: false

website:
  title: "Ariana Bardauil"
  favicon: imagenes/logo.png
  site-url: ariibard.github.io
  repo-url: https://github.com/ariibard/ariibard.github.io
  #google-analytics: "G-EX523L4LWJ"
  open-graph: true
  navbar:
    right:
      - text: Sobre mi
        file: about.qmd
      - text: Publicaciones
        file: publicaciones.qmd

  page-footer:
    left: "Ariana Bardauil" 
    center: |
      <span class="faux-block">[{{< fa brands github >}}]({{< var github-url >}}) [{{< fa brands linkedin >}}]({{< var linkedin-url >}}) </span>
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">View the source at [{{< fa brands github >}} GitHub]({{< var repo-url >}})</span>
      
format:
  html:
    theme: 
      - styles.scss




