---
title: "Hola, Soy Ari!"
listing:
  contents: 
    - /publicaciones
    - /cursos
  template: estilos/listing.ejs
  sort: "date desc"
  type: default
  image-align: right
  max-description-length: 175
  date-format: medium
  categories: false
  sort-ui: false
  filter-ui: false
  max-items: 5
  feed: false
page-layout: full
title-block-banner: false
---

::: {.text-center .btn-group role="group" aria-label="About"}
<a href="about.html"> <button type="button" class="btn btn-primary me-md-2 btn-sm">Read in english</button> </a> <a href="about_es.html"> <button type="button" class="btn btn-primary me-md-2 btn-sm">Leer en español</button> </a>
:::

**Soy politóloga especializada en ciencia de datos**, con formación de posgrado en estadística y experiencia técnica en el análisis de datos sociales y sanitarios. Actualmente curso la **Maestría en Generación y Análisis de Información Estadística (UNTREF)** y la **Especialización en Teledetección y SIG (UNLu)**.

Mi trabajo combina el diseño e implementación de soluciones analíticas con programación en **R**, **Python** y **SQL**, aplicadas al procesamiento de bases complejas, la automatización de reportes y la visualización de datos. He desarrollado tableros interactivos y aplicaciones en **Shiny**, así como herramientas de **minería de texto** para el análisis de medios y políticas públicas.

Actualmente soy **analista de datos** en el *Ministerio de Salud del Gobierno de la Ciudad de Buenos Aires* y **docente universitaria** en minería de texto y demografía social.

Además, participo activamente en proyectos de investigación y divulgación científica, y coordino iniciativas como el [**Núcleo de Innovación Social**](https://nucleodeinnovacionsocial.com.ar/) y [*Dicen los Medios*.](https://dicenlosmedios.com.ar/)

 También soy **co-organizadora de [R en Buenos Aires](https://renbaires.github.io/)**[,](https://renbaires.github.io/) una comunidad dedicada a compartir experiencias, talleres y conocimientos sobre ciencia de datos en R.

------------------------------------------------------------------------

## ltimas contribuciones

::: {#publicaciones}
:::

::: {style="text-align: right"}
[Ver todas ](publicaciones.html)
:::



